### ISSUE TITLE
Unclear test case details for bogus REST GC request

### ISSUE THREAD

**Issue by mcechini** [opengeospatial/ets-wmts10#31]
For the wmts:Server.RESTful.HTTP.Mandatory test...

It unclear what the actual URL request will look like for the following test item.  I was not able to reproduce or detect the failure. 

1.  the request invokes a URL that consists of the ServiceMetadataURL advertised in the Service Metadata document, concatenated with "/Bogus".

**Comment by dstenger** [comment]
Following is tested:
```
  A request for an unsupported type (example/unknown) of ServiceMetadata resource 
  (as specified by the Accept request header) must return an error response with 
  status code 406 (Not Acceptable). The target URI of the GET request is extracted 
  from a ServiceMetadataURL element appearing in the service description.
```

For more detail please also see last comments of https://github.com/opengeospatial/ets-wmts10/issues/24

**Comment by bermud** [comment]
@mcechini, can you please provide more details about this issue? The request you are making and the complete error you are getting. Thank you!

**Comment by mcechini** [comment]
Just trying to figure out how to mock up this request.  Given our GC available [here](http://gibs.earthdata.nasa.gov/wmts/epsg4326/best/1.0.0/WMTSCapabilities.xml), please provide a sample curl command that can be used to test.

**Comment by lgoltz** [comment]
The test wmts:Server.RESTful.HTTP.Mandatory does not append '/Bogus' to the service metadata URL. As described in https://github.com/opengeospatial/ets-wmts10/issues/31#issuecomment-271285636 the Capabilities are requested with an unsupport accept header (example/unknown).

The curl command should be:  `curl -H "Accept: example/unknown" <SERVICE_METADATA_URL>` where <SERVICE_METADATA_URL> is the service metadat url from the capabilities ("$wmts.capabilities.doc/wmts:ServiceMetadataURL/@xlink:href").

**Comment by mcechini** [comment]
If that's the case, then it sounds like the test description is incorrect or what you are describing is a totally different test and the details of this one are still unclear.

**Comment by lgoltz** [comment]
The test you mention by name and describe in https://github.com/opengeospatial/ets-wmts10/issues/31#issue-186854523 are not the same.  _wmts:Server.RESTful.HTTP.Mandatory_ is the one described in https://github.com/opengeospatial/ets-wmts10/issues/31#issuecomment-295611321. 
The test you describe in https://github.com/opengeospatial/ets-wmts10/issues/31#issue-186854523 seems to be the test _wmts:Server.RESTful.InvalidQueryString_.

The test _wmts:Server.RESTful.InvalidQueryString_ takes the capabilities URL from the capabilities, appends '/Bogus' and sends them as GET Request. Expected is that the response status code is 404. 

The curl command is `curl <BOGUS_SERVICE_METADATA_URL>` where <BOGUS_SERVICE_METADATA_URL> consist of the metadata url from the capabilities ("$wmts.capabilities.doc/wmts:ServiceMetadataURL/@xlink:href") with appended '/Bogus'. Some special cases must be considered:
 * if the metadata url ends with '?' this is removed:
   * http://localhost:8080/test? becomes http://localhost:8080/test/Bogus
 * if the metadata url ends with '.xml'  Bogus is added:
   * http://localhost:8080/test/abc.xml becomes http://localhost:8080/test/abcBogus.xml
 * Otherwise:
   * http://localhost:8080/test/abc becomes http://localhost:8080/test/abc/Bogus

**Comment by mcechini** [comment]
Ok, I  must have gotten confused by the interface when pulling out that reference number.  But I now have the information I was looking for in your last comment.  Thanks.
