### ISSUE TITLE
Test Server.KVP.GET.HTTP.Mandatory is flawed

### ISSUE THREAD

**Issue by cmorriscmps** [opengeospatial/ets-wmts10#73]
The test Server.KVP.GET.HTTP.Mandatory doesn't use any of the endpoints advertised in the Capabilities doc, but modifies the capabilities URL to create its own endpoint to submit a request to.  Since the request is not legitimate, there should be no expectations of the response.  For instance, a 200, 400, or 500 response with an error message is just as legitimate as the 404 response the test is looking for.

I suggest removing the test altogether.

**Comment by dstenger** [comment]
Thank you for reporting.
We will check your proposal.

**Comment by ghobona** [comment]
The code for this test is [here](https://github.com/opengeospatial/ets-wmts10/blob/master/src/main/scripts/ctl/wmtsServerCommonOperationsTests.xml#L149).

The code states that the test is "Test that a WMTS server observes the rules and conventions governing the use of HTTP GET operations".

The [documentation](https://cite.opengeospatial.org/teamengine/about/wmts/1.0.0/site/ats.html#Server.KVP.GET.HTTP.Mandatory) references pages 73 to 74.

A screenshot of the relevant test is attached. Notice that the specification of the Test Method was never completed. In fact, it was declared as "TBD".

![Screenshot 2023-01-19 at 10 56 51](https://user-images.githubusercontent.com/18121038/213425370-7621cf2d-7a1b-4f1f-a736-3e7c438c80b8.png)

As the Test Method was never specified, the test should be commented out (i.e. deactivated) in the ETS.

@bpross-52n When you comment out the test, please add a link back to this GitHub Issue so that there is a record of why the code was commented out.
